/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module fsm_5(clk, reset_n, din, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  input clk;
  input din;
  output dout;
  wire [2:0] present_state;
  input reset_n;
  sky130_fd_sc_hd__nor2_1 _69_ (
    .A(_56_),
    .B(_55_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__or2_0 _70_ (
    .A(_56_),
    .B(_55_),
    .X(_41_)
  );
  sky130_fd_sc_hd__nand2_1 _71_ (
    .A(_57_),
    .B(_41_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__nand2_1 _72_ (
    .A(_56_),
    .B(_31_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__nor2_1 _73_ (
    .A(_55_),
    .B(_43_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__nand2b_1 _74_ (
    .A_N(_57_),
    .B(_38_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__o211ai_1 _75_ (
    .A1(_38_),
    .A2(_44_),
    .B1(_45_),
    .C1(_42_),
    .Y(_46_)
  );
  sky130_fd_sc_hd__or2_0 _76_ (
    .A(_58_),
    .B(_46_),
    .X(_37_)
  );
  sky130_fd_sc_hd__nand2b_1 _77_ (
    .A_N(_58_),
    .B(_46_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nor2b_1 _78_ (
    .A(_56_),
    .B_N(_55_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__nor2_1 _79_ (
    .A(_57_),
    .B(_38_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__nand3_1 _80_ (
    .A(_56_),
    .B(_55_),
    .C(_31_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__a21oi_1 _81_ (
    .A1(_38_),
    .A2(_49_),
    .B1(_48_),
    .Y(_50_)
  );
  sky130_fd_sc_hd__o21a_1 _82_ (
    .A1(_47_),
    .A2(_50_),
    .B1(_42_),
    .X(_51_)
  );
  sky130_fd_sc_hd__or2_0 _83_ (
    .A(_58_),
    .B(_51_),
    .X(_34_)
  );
  sky130_fd_sc_hd__o21ai_0 _84_ (
    .A1(_56_),
    .A2(_57_),
    .B1(_38_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__mux2i_1 _85_ (
    .A0(_49_),
    .A1(_41_),
    .S(_57_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__o21ai_0 _86_ (
    .A1(_38_),
    .A2(_53_),
    .B1(_52_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__nand2b_1 _87_ (
    .A_N(_58_),
    .B(_54_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__a22o_1 _88_ (
    .A1(_38_),
    .A2(_44_),
    .B1(_48_),
    .B2(_40_),
    .X(_39_)
  );
  sky130_fd_sc_hd__or2_0 _89_ (
    .A(_58_),
    .B(_54_),
    .X(_33_)
  );
  sky130_fd_sc_hd__nand2b_1 _90_ (
    .A_N(_58_),
    .B(_51_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__dfbbp_1 _91_ (
    .CLK(clk),
    .D(present_state[0]),
    .Q(present_state[0]),
    .Q_N(_59_),
    .RESET_B(_63_),
    .SET_B(_64_)
  );
  sky130_fd_sc_hd__dfbbp_1 _92_ (
    .CLK(clk),
    .D(present_state[1]),
    .Q(present_state[1]),
    .Q_N(_60_),
    .RESET_B(_65_),
    .SET_B(_66_)
  );
  sky130_fd_sc_hd__dfbbp_1 _93_ (
    .CLK(clk),
    .D(present_state[2]),
    .Q(present_state[2]),
    .Q_N(_61_),
    .RESET_B(_67_),
    .SET_B(_68_)
  );
  assign _09_ = _61_;
  assign _68_ = _37_;
  assign _67_ = _36_;
  assign _65_ = _34_;
  assign _63_ = _32_;
  assign _56_ = present_state[1];
  assign _55_ = present_state[0];
  assign _57_ = present_state[2];
  assign _31_ = _61_;
  assign _38_ = din;
  assign _58_ = reset_n;
  assign dout = _39_;
  assign _64_ = _33_;
  assign _66_ = _35_;
endmodule
